<?php ?>
<p>To use this module, please enter your sendSMS login credentials inside the configuration page.</p><br />
<p>You don't have a sendSMS account?<br />
    Register FREE <a href="http://www.sendsms.ro/en" target="_blank">here</a>.<br />
    For more details, contact us <a href="https://www.sendsms.ro/en/contact-2/">here</a>.</p>
<p>In the settings page, under credentials, you will find a field for every order status avaible in Magento. </p>
<p>You will need to enter a message to send an SMS for the order status.</p>
<p>You can enter variables which will be filled based on the order informations.</p>
<p>Example: <strong>Good day {billing_first_name}. Your order with the {order_number} is completed.</strong></p>
<p>Please don't use diacritics. If you use them, they will be replaced with their equivalent</p>