<?php ?>

<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            $(function() {
                $(document).on('keyup', 'div.sendsms-char-count-filtered textarea', function(event) {
                    var notice = $(document).find('.admin__field-note span')[0];
                    $(notice).html(lenghtCounter($(this).val()));
                });
            });
        });

    function lenghtCounter(message) {
        var lenght = message.length;
        var messages = lenght / 160 + 1;
        if (lenght > 0) {
            if (lenght % 160 === 0) {
                messages--;
            }
            return "Number of messages: " + Math.floor(messages) + " (" + lenght + ")";
        } else {
            return "The field is empty";
        }
    }

    function checkPrice(phonesno, price) {
        if (phonesno == 0 || price == 0) {
            alert("Please filter at least a phone number or send at least one SMS");
        } else {
            message = document.querySelectorAll('div.sendsms-char-count-filtered textarea')[0].value;
            var lenght = message.length;
            var messages = lenght / 160 + 1;
            if (lenght > 0) {
                if (lenght % 160 === 0) {
                    messages--;
                }
            } else {
                messages = 0;
            }
            alert("The estimate price is of " +
                parseFloat(Math.floor(messages) * price * phonesno).toPrecision(4) +
                " euro.")
        }
    }
</script>