<form class="form" action="<?= $block->escapeHtml($block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true])) ?>" method="post">
    <input name="form_key" type="hidden" value="<?= \Magento\Framework\App\ObjectManager::getInstance()
                                                    ->get(\Magento\Framework\Data\Form\FormKey::class)
                                                    ->getFormKey(); ?>" />
    <div class="fieldset-wrapper">
        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field">
                    <label for="phone" class="admin__field-label">
                        <span>Phone</span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" id="phone" name="phone" class="admin__control-text" required>
                    </div>
                </div>
                <div class="admin__field">
                    <label for="gdpr" class="admin__field-label">
                        <span>Add unsubscribe link?</span>
                    </label>
                    <div class="admin__field-control">
                        <input type="checkbox" id="gdpr" name="gdpr" class="admin__control-checkbox-inline">
                    </div>
                </div>
                <div class="admin__field">
                    <label for="short" class="admin__field-label">
                        <span>Minimize urls?</span>
                    </label>
                    <div class="admin__field-control">
                        <input type="checkbox" id="short" name="short" class="admin__control-checkbox-inline">
                    </div>
                </div>
                <div class="admin__field">
                    <label for="message" class="admin__field-label">
                        <span>Message</span>
                    </label>
                    <div class="admin__field-control">
                        <textarea id="message" name="message" 
                            class="admin__control-textarea sendsms-char-count" required></textarea>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label"></label>
                    <div class="admin__field-control">
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action submit primary" title="Send Message">
                                    <span>Send Message</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</form>